### ISSUE TITLE
Permanent restarting

### ISSUE THREAD

**Issue by toudidel** [andresvidal/rpi3-mongodb3#3]
`docker ps` shows always the same status: _Restarting (100) n seconds ago_

The effect is I cannot connect with _docker exec -it rpi3-mongodb3 mongo admin_.
Response is always the same:
`Error response from daemon: Container abcd1234 is restarting, wait until the container is running`

**Comment by andresvidal** [comment]
Can you paste info on your docker installation and platform? Also paste the command you’re using to create a new container. Have you tried deleting and re-downloading the image?

**Comment by toudidel** [comment]
I get fresh raspbian image and now rpi3-mongodb3 works fine. I have no idea now what was the reason.

**Comment by ArkFreestyle** [comment]
Hi, this is kind of late but this should help people in the future:

Exit status 100 means that a mongod.lock file exists in the /data/db directory, if this file exists mongoDB assumes it is already running and can not start. Meanwhile your docker container keeps trying to restart it because of the restart: always flag. That's why you see Restarting (100) constantly with docker ps.

The way I fixed this is to manually run the command:

`sudo rm /data/db/mongod.lock`

This removes the lock file and mongoDB resumes operation normally. I am currently attempting to include this command in the docker-entrypoint.sh script for this image, I wanted to make a new issue for this but saw that two issues were already created and closed. If I succeed, would it be okay if I send a pull request andresvidal?
